server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


      server:
        webmvc:
          routes:
            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path=/api/v1/auth/**
            - id: ms-personas
              uri: lb://ms-persona
              predicates:
                - Path=/api/v1/personas/**
            - id: ms-equipo
              uri: lb://ms-equipo
              predicates:
                - Path=/api/v1/equipo/**
            - id: ms-tickets
              uri: lb://ms-ticket
              predicates:
                - Path=/api/v1/ticket/**
            - id: ms-diagnostico
              uri: lb://ms-diagnostico
              predicates:
                - Path=/api/v1/diagnostico/**
            - id: ms-pagos
              uri: lb://ms-pagos
              predicates:
                - Path=/api/v1/pagos/**
            - id: ms-notificaciones
              uri: lb://ms-notificaciones
              predicates:
                - Path=/api/v1/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true