spring.application.name=eureraServer

#Puerto estandar:
server.port=8761

#para que no se registre a si mismo el servidor.
eureka.client.register-with-eureka=false

#Impide que el servidor  interte descargar el registro de clientes de modo local
eureka.client.fetch-registry=false


